### ISSUE TITLE
Avoid escaping the hooks through fresh LoadLibrary or MemoryModule?

### ISSUE THREAD

**Issue by danielgindi** [cuckoosandbox/monitor#20]
I bumped into this article:
http://www.malwaretech.com/2013/09/fighting-hooks-with-hooks-sandbox-escape.html

This guy show a way (with example code) to escape hook, by making `LoadLibrary` load a fresh copy of a specific dll.
He also mentions that there's no available code that replicated `LoadLibrary` behaviour and that this is very complex - but now there's also https://github.com/fancycode/MemoryModule, so it makes it real easy to load a library without going through `LoadLibrary`.

This makes the cuckoo monitor unreliable for the next gen malware... Are there other known methods to trace the API calls?

**Comment by jbremer** [comment]
One possibility come to mind which is currently not in-place yet but could solve this issue; intercept functions related to loading files (in this case, dlls) and place our hooks on the DLL while the DLL is being read out / mapped to memory.

However, there's quite some work to make this work properly, so this is currently not very high on our todo list (albeit interesting functionality).

**Comment by danielgindi** [comment]
This would solve it for the simpler case, but when using something like `MemoryModule` those library-loading hooks won't be called at all.

**Comment by jbremer** [comment]
You'll still be able to intercept the system calls, if just from a kernel context :)

**Comment by danielgindi** [comment]
Yes that's true :-)

**Comment by jbremer** [comment]
Going to close this issue as there's not much we can do about it and no concrete features/issues have been raised here :-)
