### ISSUE TITLE
Instruction Based hooking

### ISSUE THREAD

**Issue by yoonack** [cuckoosandbox/monitor#25]
Hi,
I just saw the update in the monitor. This new instruction hooking looks interesting. Is there any particular documentation for this type of hooking listed on the web? I am wondering how they could be used and what they are used for? Thanks a lot

**Comment by jbremer** [comment]
The commit that implements it contains the information that is currently available https://github.com/cuckoosandbox/monitor/commit/563583de17d3fdf6a091f6cdc0592904957dc069 :-)

**Comment by jbremer** [comment]
@yoonack Do you need any more information or shall we close this issue?

**Comment by jbremer** [comment]
As per my comment above, closing issue.
