### ISSUE TITLE
64 Bit analysis issue within IE 8 

### ISSUE THREAD

**Issue by ChriDr** [cuckoosandbox/monitor#26]
Hello,
I think the problem with the Monitor dll for the 64bit analyses still exist within the IE8.  I compiled the current Monitor Branch and when I start an analysis within the Internet Explorer ( with the new dll files) especially on a x64 Host, the Internet Explorer is always crashing at the beginning of the analysis. Please see the attached picture:

![ie864bitproblem](https://cloud.githubusercontent.com/assets/6873184/16726527/e6b7e572-475c-11e6-9f34-fdcf27f9c194.png)

Best regards,

**Comment by jbremer** [comment]
Can you share the entire analysis?

**Comment by ChriDr** [comment]
Thanks! Sure:

http://uploaded.net/file/h4rbmy0d

**Comment by jbremer** [comment]
Hmm, not too much luck with the exception that's being thrown. Could you try running the analysis with `mode=iexplore` regardless? And also inform me about the version of Cuckoo you're running (the Git hash)? :-)

**Comment by ChriDr** [comment]
Version of Cuckoo. Current State.
head: 26a375eccb5c1075dd5da7e0f5dac9781ec41135
fetch_head: 230205e509abece726f9ae83a8be1288a330dfdd

**Comment by jbremer** [comment]
@ChriDr if by any chance you still have this VM, I'd be happy to take a look at it for testing purposes!
Currently addressing some `monitor`-related issues, so each additional testing environment would be useful. If you have any other feedback or suggestions (provided this issue has been around for a while), do let me know as well.

**Comment by jbremer** [comment]
I think we can close this issue.. please reopen if you're interested in debugging the issue further.
