### ISSUE TITLE
how to hook?

### ISSUE THREAD

**Issue by adgarr** [cuckoosandbox/monitor#34]
As a beginner, I don't know where API  are hooked  in source code? I need some help,thinks!

**Comment by doomedraven** [comment]
1. man - https://cuckoo-monitor.readthedocs.io/en/latest/
2. hooks should be added here - https://github.com/cuckoosandbox/monitor/tree/master/sigs

**Comment by adgarr** [comment]
@doomedraven Thank you so much! But I  am most eager to see how the monitor hook function.
Can you give a example through source code? Thanks!

**Comment by doomedraven** [comment]
see any rst file from 2nd point
example

```
gethostbyname
=============

Signature::

    * Is success: ret != NULL
    * Return value: struct hostent *

Parameters::

    ** const char *name hostname

Interesting::

    s hostname
```

**Comment by adgarr** [comment]
Hi,could you tell me the followed code how to work and it's function
 while (hook(h, module_handle) == 1);

**Comment by adgarr** [comment]
@doomedraven Hi,could you tell me the followed code how to work and it's function
while (hook(h, module_handle) == 1);

**Comment by doomedraven** [comment]
your example isn't very good
but 

something like, also there no while as hook, hooks it all time when that apicall called

```
h
=============

Signature::

    * Is success: ret == 1
```

but read this: https://cuckoo-monitor.readthedocs.io/en/latest/hooks.html#creating-hooks
there is everything what you need

**Comment by adgarr** [comment]
@doomedraven Thank you so much!
but the followed is all hooked API?
static const char *g_funcnames[] = {
    "NtQueryVirtualMemory",
    "NtAllocateVirtualMemory",
    "NtFreeVirtualMemory",
    "NtProtectVirtualMemory",
    "NtReadVirtualMemory",
    "NtQueryInformationProcess",
    "NtQueryInformationThread",
    "NtQueryObject",
    "NtQueryKey",
    "NtDuplicateObject",
    "NtWriteFile",
    "NtFsControlFile",
    "NtSetInformationFile",
    "NtClose",
    "NtDelayExecution",
    "NtWaitForSingleObject",
    "NtOpenThread",
    "NtResumeThread",
    NULL,
};

**Comment by doomedraven** [comment]
__search box__ under cuckoosandbox user will be useful for you
https://github.com/cuckoosandbox/cuckoo/wiki/Hooked-APIs-and-Categories

**Comment by adgarr** [comment]
@doomedraven Thanks ！ but I want to know where the hooked APIs are hooked through C-language

**Comment by doomedraven** [comment]
is not in C style hooking, you need define hooks in yaml format, and then compile it, READ THE DOCUMENATION

**Comment by adgarr** [comment]
@doomedraven is the followed code that hook APIs?
while (hook(h, module_handle) == 1);

**Comment by doomedraven** [comment]
already answered https://github.com/cuckoosandbox/monitor/issues/34#issuecomment-257821244

is not C style hooks, it yaml, see that comment and read the documentation how to create hooks

**Comment by adgarr** [comment]
ok   thanks!  but  what it's  function

**Comment by doomedraven** [comment]
read carefully documentation and use try/error method, as it looks like you not even read the documenation, see examples from .rst about another hooked function, and use search box

**Comment by adgarr** [comment]
@doomedraven Hi, .rst just lists som functions that would be hooked. But how to hook these  functions that would be hooked from .rst. could you give me the flow ? Thanks!

**Comment by doomedraven** [comment]
get a walk of files on this repo and see hook related .c files

**Comment by adgarr** [comment]
@doomedraven I see the monitor.c and utils/process.py files,  but still be confused. I am a newcomer and
I knew the hook management from other articls.But here,I can't find the hook management from the source code .

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/monitor/search?l=C&q=hook&utf8=✓

**Comment by adgarr** [comment]
@doomedraven Think you very much! That I had seen, but still couldn't find how to hook functions

**Comment by jbremer** [comment]
What @doomedraven said, take a proper look at the code.
