### ISSUE TITLE
sig_hook()

### ISSUE THREAD

**Issue by adgarr** [cuckoosandbox/monitor#35]
the sig_hook() was defined by followed code hook_t *sig_hooks() in hooking.h file. But I can't find where the  sig_hook() was achieved .

**Comment by jbremer** [comment]
Compile the Cuckoo Monitor and run `grep -r sig_hook` on the command line.

**Comment by adgarr** [comment]
@jbremer Thank you very much ! Can you tell briefly me the sig_hook() how to work and it's　function。Thanks again!
