### ISSUE TITLE
Why hooked both native and Win32 APIs ?

### ISSUE THREAD

**Issue by u-riaz** [cuckoosandbox/monitor#38]
You people have hooked both versions i.e. native and Win32 API. Means for registry, you hooked APIs from advapi32 as well as from ntdll, but i think, advapi32 calls will go through ntdll and we can catch the events only by hooking ntdll. Same is true for many other hooks e.g. File Hooks, Process Hooks etc.
What is the motivation/theme behind hooking both versions? Can we not get all the information by only hooking native APIs? Hooking only native, will keep the hook counter lower and we will get coverage of both native & win32 (because win32 calls native internally).
Thanks !

**Comment by jbremer** [comment]
Sorry for the late reply. In most cases you get more higher level information if you hook the win32 functions as opposed to the native API. That's pretty much the only reason. Hope it answers your question :-)

**Comment by jbremer** [comment]
I think this issue can be closed now.
