### ISSUE TITLE
File renamed using NtSetInformationFile are not tracked

### ISSUE THREAD

**Issue by mvdnes** [cuckoosandbox/monitor#44]
I recently encountered a sample that used NtSetInformationFile to rename a file. This callback is present in the signatures (under sigs/file_native.rst), but only handles the 'remove' case.
The file renamed this way could not be upload since the agent could not correctly determine the location of the file at the end of the execution.

I tried to implement the signalling of the renaming function, but I could not come up with a clean solution on handling the case where the RootDirectory HANDLE is not NULL.

**Comment by jbremer** [comment]
Thanks for the suggestion! I'm going to have a look later :-)
If in the meanwhile you're able to share a sample or implement a test application that performs this exact functionality, would save me a bit of time.

**Comment by jbremer** [comment]
Ran into the same issue recently, should now be resolved, see also d2d15be510ae26a9fae6606cfaf1bfdc250855ef. Currently working on getting a bunch of monitor fixes back to upstream, but needs some more time :-) If the above doesn't resolve your issue, let me know.
Oh, saw the `RootDirectory` just now.. let me fix that as well (if you have a sample / test case where that's used, let me know) ;-)

**Comment by jbremer** [comment]
Alright, there we go. Will close this issue for now - assuming all's fine.

**Comment by mvdnes** [comment]
Thanks! 👍 My example did not use the RootDirectory, so I will assume it is fine as well. I like your solution using `InitializeObjectAttributes`.

**Comment by jbremer** [comment]
Gotcha - yeah, gotta you use that functionality that's already existing, eh :)
