### ISSUE TITLE
Internal Server Error for url: http:/192.168.56.101:800/mkdtemp

### ISSUE THREAD

**Issue by daleprice10** [cuckoosandbox/monitor#67]
When an analysis is almost complete, both file and URL, the server throws a "Failure in AnalysisManager.run" error message. 
After the Traceback, the "HTTP Error: 500 Server Error: Internal Server Error for url: http:/192.168.56.101:800/mkdtemp" is reported. 

I have reviewed a number of documents and I have tried a number of updates without any success.

Please assist.
[cuckoo.log](https://github.com/cuckoosandbox/monitor/files/2275659/cuckoo.log)

**Comment by daleprice10** [comment]
Thank you in advance for your assistance. It is greatly appreciated.

**Comment by doomedraven** [comment]
that isn't a monitor isssue for first, the second one, why port is 800? when port is 8000

**Comment by daleprice10** [comment]
Sorry, that 800 is a typo? It is port 8000. Using curl to access the URL works fine.

Where can I post to get assistance. Thanks.

**Comment by doomedraven** [comment]
stay here, you should be in cuckoo project, not in cuckoo monitor, but well lets kill it here, 

now when you open an issue, provide as much info as possible, about everything to be able to help you, if no we spend time for asking stupid questions

**Comment by daleprice10** [comment]
Thank you. Best.
