### ISSUE TITLE
monitor crash.  attachment unzip password:virus

### ISSUE THREAD

**Issue by ne1llee** [cuckoosandbox/monitor#68]
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: RtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: f7 f1 56 89 14 24 8b 0c 24 83 c4 04 9c 53 0f 02 exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x32010 exception.instruction: div ecx exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0xc0000094 exception.offset: 204816 exception.address: 0x432010 registers.esp: 1245028 registers.edi: 0 registers.eax: 4399258 registers.ebp: 1245076 registers.edx: 0 registers.ebx: 2147299328 registers.esi: 0 registers.ecx: 0 | 1 | 0 | 0
-- | -- | -- | -- | --
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: RtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: 9d 60 81 c7 fc 39 00 00 81 ee cb 04 00 00 61 3b exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x32032 exception.instruction: popfd exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0x80000004 exception.offset: 204850 exception.address: 0x432032 registers.esp: 1245024 registers.edi: 0 registers.eax: 1 registers.ebp: 1245076 registers.edx: 4 registers.ebx: 2147299328 registers.esi: 0 registers.ecx: 3 | 1 | 0 | 0
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: RtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: 31 31 74 03 75 01 eb cc 3d 75 55 27 e8 9c 72 e6 exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x32247 exception.instruction: xor dword ptr [ecx], esi exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0xc0000005 exception.offset: 205383 exception.address: 0x432247 registers.esp: 1245028 registers.edi: 4399709 registers.eax: 1994406963 registers.ebp: 1245076 registers.edx: 4397380 registers.ebx: 2147299328 registers.esi: 0 registers.ecx: 0 | 1 | 0 | 0
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: RtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: 31 3b 56 68 36 81 95 05 5e 5e cc 36 96 f3 93 e3 exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x3190b exception.instruction: xor dword ptr [ebx], edi exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0xc0000005 exception.offset: 203019 exception.address: 0x43190b registers.esp: 1245028 registers.edi: 0 registers.eax: 1994406963 registers.ebp: 1245076 registers.edx: 4397380 registers.ebx: 0 registers.esi: 4397339 registers.ecx: 0 | 1 | 0 | 0
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: RtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: cc 02 eb e8 23 c7 e8 0a 00 00 00 0b c5 f9 e9 07 exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x306d3 exception.instruction: int3 exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0x80000003 exception.offset: 198355 exception.address: 0x4306d3 registers.esp: 1245024 registers.edi: 0 registers.eax: 2156199220 registers.ebp: 1245076 registers.edx: 0 registers.ebx: 2147299328 registers.esi: 0 registers.ecx: 0 | 1 | 0 | 0
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: RtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: f7 f1 56 89 14 24 8b 0c 24 83 c4 04 9c 53 0f 02 exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x309bf exception.instruction: div ecx exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0xc0000094 exception.offset: 199103 exception.address: 0x4309bf registers.esp: 1245024 registers.edi: 0 registers.eax: 4393545 registers.ebp: 1245076 registers.edx: 0 registers.ebx: 2147299328 registers.esi: 0 registers.ecx: 0 | 1 | 0 | 0
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: RtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: 9d 60 81 c7 fc 39 00 00 81 ee cb 04 00 00 61 3b exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x309e1 exception.instruction: popfd exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0x80000004 exception.offset: 199137 exception.address: 0x4309e1 registers.esp: 1245020 registers.edi: 0 registers.eax: 1 registers.ebp: 1245076 registers.edx: 4 registers.ebx: 2147299328 registers.esi: 0 registers.ecx: 3 | 1 | 0 | 0
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x30def @ 0x430defRtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: 8b 0b b9 01 00 00 00 eb 0d b9 00 00 00 00 64 a1 exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x30f54 exception.instruction: mov ecx, dword ptr [ebx] exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0xc0000005 exception.offset: 200532 exception.address: 0x430f54 registers.esp: 1244980 registers.edi: 0 registers.eax: 4394845 registers.ebp: 1245024 registers.edx: 38 registers.ebx: 1996554240 registers.esi: 0 registers.ecx: 0 | 1 | 0 | 0
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x30def @ 0x430defRtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: 8b 0b b9 01 00 00 00 eb 0d b9 00 00 00 00 64 a1 exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x30f54 exception.instruction: mov ecx, dword ptr [ebx] exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0xc0000005 exception.offset: 200532 exception.address: 0x430f54 registers.esp: 1244980 registers.edi: 0 registers.eax: 4394845 registers.ebp: 1245024 registers.edx: 38 registers.ebx: 1996619776 registers.esi: 0 registers.ecx: 0 | 1 | 0 | 0
__exception__Oct. 8, 2018, 4:37 p.m. | stacktrace: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x30def @ 0x430defRtlInitializeExceptionChain+0xef RtlFreeSid-0x117 ntdll+0x637f5 @ 0x77b437f5 RtlInitializeExceptionChain+0xc2 RtlFreeSid-0x144 ntdll+0x637c8 @ 0x77b437c8 exception.instruction_r: 8b 0b b9 01 00 00 00 eb 0d b9 00 00 00 00 64 a1 exception.symbol: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c+0x30f54 exception.instruction: mov ecx, dword ptr [ebx] exception.module: 32ecf7b6f170494544675f32d6f74f5d6b39cc8c.exe exception.exception_code: 0xc0000005 exception.offset: 200532 exception.address: 0x430f54 registers.esp: 1244980 registers.edi: 0 registers.eax: 4394845 registers.ebp: 1245024 registers.edx: 38 registers.ebx: 1996685312 registers.esi: 0 registers.ecx: 0
[virus.zip](https://github.com/cuckoosandbox/monitor/files/2455298/virus.zip)

**Comment by stoerchl** [comment]
Was there ever a solution / workaround to this problem? 
Having a very similar crash whenever I submit an office document. 
```
exception.module: monitor-x86.dll
exception.exception_code: 0x80000004
```
Using the newest monitor DLL as far as I know `e071e63a66e831163a40abc45109fdf71fee829e`

**Comment by doomedraven** [comment]
which office version?

**Comment by stoerchl** [comment]
Office Home and Business 2016 - 16.0.11029.20079
Also tried to compile the newest monitor sources from github but it still does not work.

**Comment by doomedraven** [comment]
2007 latest supported version

**Comment by stoerchl** [comment]
office 2007 is the latest supported version for cuckoo? i'm using office 2013 on another setup and it works just fine.

**Comment by doomedraven** [comment]
you can see tons of issues about office 2013 not working properly for some persons
