### ISSUE TITLE
Hooking additional functions

### ISSUE THREAD

**Issue by DainTorson** [cuckoosandbox/monitor#80]
Hello!

Is there any way to define some additional functions to be hooked? I've found some .rst files, which contain definitions of hooked functions. What is this .rst format? Can I modify these files in order to hook some other functions?

Thanks in advance!

**Comment by doomedraven** [comment]
RTM

**Comment by DainTorson** [comment]
@doomedraven 

Woops. sorry, haven't noticed that there is documentation specifically for monitor.

**Comment by doomedraven** [comment]
np :) enjoy it
